# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - '**.md'
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      file_path:
        description: 'markdown file path'
        required: true
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Generate pdf
        run: |
          git log -n 10
          for file in $(git diff $GITHUB_SHA~ $GITHUB_SHA --name-only '*.md') ; do
            echo $file
            if [ $file != "README.md" ]; then
              npx @marp-team/marp-cli@latest $file --pdf
            fi
          done

      # - name: Generate pdf
      #   run: npx @marp-team/marp-cli@latest ${{ github.event.inputs.file_path }} --pdf

      # - name: commit pdf
      #   run: npx @marp-team/marp-cli@latest slide-deck.md --pdf

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
